cli/stores.hpp, include/fiction/io/dot_drawers.hpp, include/fiction/io/print_layout.hpp, include/fiction/layouts/gate_level_layout.hpp, test/layouts/gate_level_layout.cpp
Graphviz dot drawer for layouts
=> Dot drawer

include/fiction/algorithms/design_rule_violations.hpp, include/fiction/algorithms/exact.hpp, include/fiction/algorithms/network_utils.hpp, include/fiction/algorithms/orthogonal.hpp, include/fiction/io/print_layout.hpp, include/fiction/io/write_sqd_layout.hpp, include/fiction/layouts/gate_level_layout.hpp
=> Fix several compiler warnings

README.md, docs/technology/gate_libraries.rst, experiments/bestagon/bestagon.cpp, experiments/fiction_experiments.hpp, include/fiction/technology/inml_topolinano_library.hpp, include/fiction/technology/qca_one_library.hpp, include/fiction/technology/sidb_bestagon_library.hpp
This PR introduces the *Bestagon* gate library for the SiDB technology as proposed in *Hexagons are the Bestagons: Design Automation for Silicon Dangling Bond Logic* by Marcel Walter, Samuel Sze Hang Ng, Konrad Walus, and Robert Wille in Design Automation Conference 2022.
=> SiDB Bestagon gate library

include/fiction/layouts/coordinates.hpp
Thanks to Benjamin Hien for pointing it out!
=> :bug: Fixed a compilation bug that could occur by including the same header multiple times

Dockerfile
=> :wrench: Updated the Dockerfile

.github/workflows/coverage.yml
Switched from the bash uploader to the latest GitHub action
=> :construction_worker: Updated OS and tools in the Coverage CI workflow

.github/workflows/docker-image.yml, Dockerfile
A CI workflow that builds the provided Docker image.
=> Docker Image CI

include/fiction/algorithms/path_finding/a_star.hpp, include/fiction/layouts/obstruction_layout.hpp
Many thanks to @simon1hofmann for pointing this one out!
=> :bug: Fixed a bug in crossing considerations of `obstruction_layout`s

.github/workflows/clang-format.yml, .github/workflows/clang-tidy-review.yml
This PR ensures some naming consistency across CIs.
=> :construction_worker: Changed CI name

.github/release-drafter.yml, .github/workflows/release-drafter.yml
In this PR, a Release Drafter is added to automatically maintain Draft Releases.
=> :sparkles: Release Drafter to automatically maintain a Draft Release

.github/release-drafter.yml, .github/workflows/clang-tidy-review-post.yml, .github/workflows/release-drafter.yml
Fixed some small inconsistencies in the CI system.
=> :art: CI inconsistency fixes

docs/getting_started.rst
This PR fixes an outdated note on how to find Z3, how to disable the CLI in header-only mode, and updates the installation process description on Mugen's libraries.
=> :memo: Updated notes on the installation process to the documentation

docs/layouts/coordinates.rst
Fixed an issue with some SiQAD functions being incorrectly rendered in Readthedocs.
=> :memo: Fixed namespace in SiQAD utility function documentation

test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
Just added two tests for larger layouts.
=> :white_check_mark: added test for larger layouts and three state simulation

include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp, include/fiction/technology/charge_distribution_surface.hpp, test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp, test/technology/charge_distribution_surface.cpp
a few bug fixes and additonal unit-tests added.
=> Use bitset and gray code

experiments/generating_txt_files.cpp, include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp
=> :bug: replacing ``auto`` by ``uint64_t``

include/fiction/io/write_sqd_sim_result.hpp, include/fiction/technology/charge_distribution_surface.hpp, test/io/write_sqd_sim_result.cpp
To ensure test reproducibility on all systems, this PR enforces an SiDB order in the `write_sqd_sim_result` function.
=> :white_check_mark: Ensured a reproducible SiDB order for test reproducibility

bindings/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp, bindings/pyfiction/test/layouts/test_gate_level_layout.py
=> ✨ Add gate checks to pyfiction

bindings/pyfiction/test/algorithms/simulation/sidb/test_quicksim.py
This PR uses ``assertLessEqual``.
=> :art: add ``assertLessEqual``.

bindings/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
Exposed the `is_dead` function for gate level layouts.
=> ✨ Add `is_dead` to pyfiction

.github/workflows/pyfiction-docstring-generator.yml
Upgraded `clang` from version `14` to `15.0.7` to fix the pyfiction doctoring generator.
=> 🐛 Fix docstring generator

README.md
Some slight changes to the README to better reflect what *fiction* can do.
=> :memo: Updated README to make it more approachable

include/fiction/algorithms/verification/design_rule_violations.hpp, test/algorithms/verification/design_rule_violations.cpp, test/algorithms/verification/equivalence_checking.cpp
Design-rule violation testing and equivalence checking were broken on empty gate-level layouts because they expected I/Os to be present. This PR adds checks to avoid these assumptions. Additional test cases are added to validate empty gate-level layouts.
=> :bug: Fixed design-rule violation testing and equivalence checking on empty gate-level layouts

include/fiction/technology/sidb_surface_analysis.hpp
Many thanks to @Drewniok for reporting!
=> :bug: Fixed a bug that caused pre-mature termination of `sidb_surface_analysis`

include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp, include/fiction/algorithms/simulation/sidb/critical_temperature.hpp, include/fiction/algorithms/simulation/sidb/occupation_probability_of_excited_states.hpp, test/algorithms/path_finding/distance.cpp, test/algorithms/simulation/sidb/quickexact.cpp, test/algorithms/simulation/sidb/quicksim.cpp, test/technology/sidb_nm_position.cpp, test/utils/layout_utils.cpp
This PR fixes urgent CodeQL warnings.
=> :art: Fix urgent CodeQL warnings.

experiments/fiction_experiments.hpp
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
=> :file_folder:  Case style of experiments folders corrected in fiction_experiments.hpp

.github/workflows/macos.yml
This PR adds missing single quotes to ensure successful execution of the MacOS CI.
=> :green_heart: Fix for MacOS CI

.github/workflows/macos.yml, include/fiction/algorithms/simulation/sidb/time_to_solution.hpp, include/fiction/layouts/bounding_box.hpp, include/fiction/technology/charge_distribution_surface.hpp, test/algorithms/simulation/sidb/time_to_solution.cpp, test/io/print_layout.cpp, test/technology/charge_distribution_surface.cpp
This PR includes a selection of the commits in #325 , with the relevant comments addressed.
=> :bug: Bugfix related to charge index recomputation and minor bugfixes from #325

docs/algorithms/post_layout_optimization.rst, docs/algorithms/sidb_simulation.rst, docs/publications.rst, include/fiction/algorithms/physical_design/post_layout_optimization.hpp, include/fiction/algorithms/simulation/sidb/operational_domain.hpp, include/fiction/algorithms/simulation/sidb/quickexact.hpp
This PR adds several of our latest paper references to the documentation.
=> :memo: Added latest paper references to the documentation

docs/algorithms/sidb_simulation.rst, include/fiction/algorithms/simulation/sidb/can_positive_charges_occur.hpp
A function was missing from the RST documentation.
=> :memo: Added missing RST documentation

docs/publications.rst
Changed publication year of the recent NANOARCH papers to 2023.
=> 📝 Update NANOARCH publication year

docs/publications.rst, include/fiction/algorithms/simulation/sidb/quickexact.hpp
This PR updates the reference of ``QuickExact`` to the successful publication (https://ieeexplore.ieee.org/document/10473946).
=> :memo: Update ``QuickExact`` reference.

.github/workflows/coverage.yml
This PR bumps the `codecov/codecov-action` to `v4` to fix the currently failing CI.
=> :arrow_up: Bump the Codecov action to v4

.gitmodules, include/fiction/technology/technology_mapping_library.hpp
This PR changes the _mockturtle_ submodule. It now uses the upstream version (https://github.com/lsils/mockturtle) instead of Marcel's fork (https://github.com/marcelwa/mockturtle).
=> ⬆️  Use mockturtle upstream as submodule

.github/workflows/pyfiction-pypi-deployment.yml
Assigned individual names to each wheel to prevent overwriting them.
=> 🐛 PyPI Deployment for multiple operating systems

README.md
Included our hexagonalization, post-layout optimization and wiring reduction algorithms in the README.
=> 📝 Added more physical design algorithms to the README

.github/workflows/clang-tidy-review-post.yml, .github/workflows/clang-tidy-review.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/docker-image.yml, .github/workflows/macos.yml, .github/workflows/pyfiction-docstring-generator.yml, .github/workflows/pyfiction-pypi-deployment.yml, .github/workflows/python-bindings.yml, .github/workflows/release-drafter.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
Added emojis to every workflow.
=> 🎨 Added emojis to CI/CD

bindings/pyfiction/include/pyfiction/algorithms/physical_design/post_layout_optimization.hpp, bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp, cli/cmd/physical_design/optimize.hpp, include/fiction/algorithms/physical_design/post_layout_optimization.hpp, test/algorithms/physical_design/post_layout_optimization.cpp, test/utils/blueprints/layout_blueprints.hpp
Introduced an additional flag to restrict `post_layout_optimization` to only relocate gates if a crossing-free rewiring is found.
=> :sparkles: Planar Post-Layout Optimization

.github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/macos.yml, .github/workflows/pyfiction-pypi-deployment.yml, .github/workflows/python-bindings.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, Dockerfile
This PR updates the Z3 version from ``4.10.0`` to ``4.13.0`` for the CLI workflow and the Docker container. This change is made because the docker fails on lower versions.
=> :arrow_up: Upgrade Z3 to Version 4.13.0 in CLI Workflow and Docker.

README.md, docs/cli.rst
Added missing entries of `gold` in the README and documentation of the cli command.
=> 📝 Add `gold` to README and docs

bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp, docs/algorithms/sidb_simulation.rst, include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp, test/algorithms/simulation/sidb/displacement_robustness_domain.cpp
=> :pencil2: Fixed a typo in robustness domain analysis

bindings/pyfiction/include/pyfiction/algorithms/network_transformation/technology_mapping.hpp, bindings/pyfiction/include/pyfiction/algorithms/physical_design/exact.hpp, bindings/pyfiction/include/pyfiction/algorithms/physical_design/graph_oriented_layout_design.hpp, bindings/pyfiction/include/pyfiction/algorithms/physical_design/orthogonal.hpp, bindings/pyfiction/include/pyfiction/algorithms/physical_design/post_layout_optimization.hpp, bindings/pyfiction/include/pyfiction/algorithms/physical_design/wiring_reduction.hpp, bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/critical_temperature.hpp, bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/time_to_solution.hpp, bindings/pyfiction/include/pyfiction/algorithms/verification/equivalence_checking.hpp, bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp, cli/cmd/physical_design/exact.hpp, cli/cmd/physical_design/gold.hpp, cli/cmd/physical_design/onepass.hpp, cli/cmd/physical_design/ortho.hpp, cli/stores.hpp, include/fiction/algorithms/physical_design/exact.hpp, include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp, include/fiction/algorithms/physical_design/one_pass_synthesis.hpp, include/fiction/algorithms/physical_design/orthogonal.hpp, include/fiction/algorithms/physical_design/post_layout_optimization.hpp, include/fiction/algorithms/simulation/sidb/time_to_solution.hpp, include/fiction/layouts/gate_level_layout.hpp, test/layouts/gate_level_layout.cpp
Add a tracker for the number of crossings in a layout that is automatically updated when a crossing is added or removed.
=> ✨ Track number of crossings

README.md, bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp, docs/algorithms/determine_clocking.rst, docs/publications.rst, docs/technology/hsi_lattices.rst, experiments/physical_design_with_on_the_fly_gate_design/physical_design_with_on_the_fly_gate_design.cpp, include/fiction/algorithms/physical_design/determine_clocking.hpp, include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp, include/fiction/algorithms/physical_design/on_the_fly_circuit_design_on_defective_surface.hpp, include/fiction/algorithms/physical_design/post_layout_optimization.hpp
This PR updates the documentation by including several of our latest publications from IEEE NANO 2024.
=> :memo: Added documentation on our latest papers from IEEE NANO

docs/changelog.rst
Fixes a duplication of items in the CHANGELOG.
=> :memo: Fix duplicated CHANGELOG entry

CITATION.cff
Added a `CITATION.cff` file for quick access to the repo's citation information (for users who don't want to scroll down).
=> :memo: Added a `CITATION.cff` file

docs/changelog.rst
Added changes to the changelog.
=> 📝 Update the `CHANGELOG`

include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
This PR fixes the windows CI by adding the ``fiction`` namespace to the ``to_fiction_coord`` function.
=> :green_heart: Added ``fiction`` namespace to function to fix the Windows CI

bindings/pyfiction/include/pyfiction/algorithms/verification/design_rule_violations.hpp, bindings/pyfiction/test/algorithms/verification/test_design_rule_violations.py
Output DRV report using `pybind's` print function to be able to capture it in Python.
=> 🐍 Use `pybind's` print function to output the DRV report

docs/changelog.rst, docs/publications.rst
Added the recently published paper: "Late Breaking Results: Wiring Reduction for Field-coupled Nanotechnologies" to the publication list.
=> 📝 Added wiring reduction paper to publication list

.github/workflows/pyfiction-pypi-deployment.yml, pyproject.toml
Adjusted deployment target for the Python bindings under macOS to version 11.0.
=> :apple: Adjusted deployment target for macOS

docs/conf.py, pyproject.toml
This PR adds @wlambooy as an author to the framework documentation and metadata.
=> :memo: Added Willem Lambooy as author to the framework

docs/changelog.rst
Update the CHANGELOG to include all the latest updates.
=> :memo: Update the CHANGELOG

docs/publications.rst
This PR adds the paper ``Towards Atomic Defect-Aware Physical Design of Silicon Dangling Bond Logic on the H-Si $(100)-2\times 1$ Surface`` by Walter (@marcelwa) et al. to the publication list.
=> :memo: Added defect-aware physical design paper from DATE 2024.

.github/workflows/pyfiction-pypi-deployment.yml
This PR updates the workflow building the wheels to reduce runtime by excluding redundant combinations of OSs and Python versions
=> :construction_worker: Reduce workflow load when building wheels

.github/renovate.json5
Fixed git submodule management with Renovate.
=> :wrench: Fix submodule management with Renovate

.github/workflows/macos.yml, .github/workflows/pyfiction-pypi-deployment.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, include/fiction/io/dot_drawers.hpp, include/fiction/technology/charge_distribution_surface.hpp
This PR adds ARM64 CI runs on Linux because GitHub made them publicly available today.
=> :construction_worker: Added ARM64 CI runs on Linux

.github/workflows/pyfiction-pypi-deployment.yml
Wheels did not have a unique name and therefore got overridden.
=> 🐍 Unique Wheel Names

bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp, docs/publications.rst, include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp, include/fiction/algorithms/physical_design/post_layout_optimization.hpp
=> 📝 Add LASCAS and TCAD papers to docs

bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp, docs/publications.rst, include/fiction/algorithms/simulation/sidb/defect_influence.hpp
This PR adds the reference to _QuickTrace: An Efficient Contour Tracing Algorithm for Defect Robustness Simulation of Silicon Dangling Bond Logic_ (https://ieeexplore.ieee.org/document/11044082) presented on ISCAS 2025.
=> :memo: Added ISCAS 2025 reference
