- include/fiction/io/read_fqca_layout.hpp
`std::regex_replace` behaves differently under macOS compared to Windows and Linux. This PR fixes an issue with string substitution.
> macOS fix for `read_fqca_layout`

- experiments/bestagon/bestagon.cpp
If Z3 was not enabled, attempting to build the Bestagon experiment lead to a compilation error. This has been fixed.
> :rotating_light: Make sure the Bestagon experiment is not compiled if Z3 is not found

- .github/workflows/coverage.yml
- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- docs/getting_started.rst
- libs/mugen/requirements.txt
This PR updates the GitHub Action CI scripts to access the latest OS and tool versions for all builds. This is particularly important for the macOS 10.15 runners which were already deprecated and recently saw a scheduled brownout.
> Update GitHub Action CI Runners and Dependencies

- .github/workflows/windows.yml
This fixes Z3 linking on Windows CI with VS 2022.
> :green_heart: Upgraded toolset to v143 for Visual Studio 2022 CI builds

- README.md
- docs/cli.rst
- docs/publications.rst
- docs/technology/gate_libraries.rst
Added BibTeX citation and a paper link for the Bestagon library to the documentation.
> Bestagon bibliography

- .github/workflows/ubuntu.yml
- CMakeLists.txt
- cmake/FindTBB.cmake
- docs/getting_started.rst
- libs/CMakeLists.txt
GCC requires TBB to benefit from potential performance gains when using parallel STL algorithms. This PR introduces automatic linking against TBB if found on the system.
Should the implementation status of [P0024R2](https://en.cppreference.com/w/cpp/compiler_support/17) be updated in the future, the changes from this PR can be reverted.
> :construction_worker: Enabled automatic linking with TBB when compiling with GCC to enable parallel STL algorithms

- .github/workflows/coverage.yml
- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- Dockerfile
- cmake/FindZ3.cmake
- libs/CMakeLists.txt
Make use of [cda-tum/setup-z3](https://github.com/cda-tum/setup-z3) to seamlessly install Z3 in the action runners. This alleviates quite a bit of the legacy burden that came with self-compiling Z3. Consequently, the build times could be sped up significantly.
Many thanks to @burgholzer for his efforts!
> :construction_worker: Z3 setup action

- .github/workflows/coverage.yml
- .github/workflows/docker-image.yml
- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
Using [`hendrikmuhs/ccache-action`](https://github.com/marketplace/actions/ccache-for-gh-actions), build times of the CI jobs are significantly sped up via caching.
> :construction_worker: Enable `ccache` for GitHub Action runners

- include/fiction/io/dot_drawers.hpp
- test/networks/technology_network.cpp
- `write_dot_layout` called the wrong DOT drawer
- `technology_network` was not sufficiently checked for function creation traits
> :bug: Fixed a bug with layout DOT drawers and a small inconsistency in the tests

- CMakeLists.txt
As a result of the flag being ignored, the build system would not be able to find the pyfiction build target.
> Bug fix: FICTION_PYTHON_BINDINGS flag was ignored

- .github/workflows/clang-tidy-review-post.yml
- .github/workflows/clang-tidy-review.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/docker-image.yml
- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
This PR adapts the CI workflows such that they are only run when files have changed which could affect their outcome. Thereby, less time should be spent running redundant CIs.
> :construction_worker: Run CI only when necessary

- .github/workflows/clang-format.yml
This PR adds a linter using [`ClangFormat`](https://clang.llvm.org/docs/ClangFormat.html). It automatically applies proposed changes to PRs and pushes to `main`.
> :construction_worker: Added a ClangFormat linter workflow

- include/fiction/algorithms/path_finding/distance.hpp
> :zap: Made distance functions `constexpr`

- include/fiction/algorithms/graph/graph_coloring.hpp
- test/algorithms/graph/graph_coloring.cpp
- test/algorithms/physical_design/color_routing.cpp
This bug occurred when clique information was provided for mutex cliques of the same size. The SAT solver would then not be able to find a proper coloring anymore and the attempt would fail.
Many thanks to @simon1hofmann for reporting!
> :bug: Fixed a bug in SAT-based graph coloring

- include/fiction/algorithms/graph/graph_coloring.hpp
- test/algorithms/physical_design/color_routing.cpp
The bug occurred when clique information was provided for mutex cliques. The algorithm now falls back to MCS coloring.
> :bug: Fixed a bug in SAT-based graph coloring (this time for real)

- cli/cmd/io/blif.hpp
- cli/cmd/io/fqca.hpp
- cli/cmd/io/qca.hpp
- cli/cmd/io/qcc.hpp
- cli/cmd/io/qll.hpp
- cli/cmd/io/sqd.hpp
- include/fiction/io/print_layout.hpp
- include/fiction/types.hpp
- test/io/print_layout.cpp
Some filenames would get lost when writing layouts or networks. Also, printed ASCII layouts would look weird. Both have been fixed.
> :bug: Fixed several I/O issues

- include/fiction/algorithms/graph/generate_edge_intersection_graph.hpp
- test/algorithms/physical_design/color_routing.cpp
The bug prevented crossing flags from being passed through to Yen's algorithm when a path limit was specified. Many thanks to @simon1hofmann for reporting!
> :bug: Fixed a bug in `color_routing` 

- include/fiction/layouts/cartesian_layout.hpp
- include/fiction/layouts/obstruction_layout.hpp
- test/algorithms/physical_design/color_routing.cpp
- test/layouts/obstruction_layout.cpp
`obstruction_layout` was not properly tuned to gate-level layouts in the `is_obstructed_connection` case. This has been fixed.
> :bug: Added additional checks for `is_obstructed_connection` to ensure proper handling of crossing cases

- include/fiction/algorithms/simulation/sidb/sidb_simulation_parameters.hpp
- include/fiction/technology/sidb_nm_position.hpp
Enabled `constexpr` and added missing documentation.
> :art: Small inconsistency fix

- include/fiction/technology/charge_distribution_surface.hpp
The function `potential_between_sidbs` in `charge_distribution_surface` was accessing a non-existing variable, which caused compilation to fail if this function was called. This PR fixes the behavior.
> :bug: Fixed accessing non-existing variables in `potential_between_sidbs`

- include/fiction/technology/charge_distribution_surface.hpp
- test/technology/charge_distribution_surface.cpp
In this PR, one function is renamed to appropriately reflect its role. Additionally, missing tests for ``potential_between_sidbs`` are added.
> :adhesive_bandage: Renamed functions to more appropriately reflect their role

- README.md
- docs/algorithms/sidb_simulation.rst
- docs/publications.rst
- include/fiction/algorithms/simulation/sidb/quicksim.hpp
This PR adds the missing design automation algorithms to the README and documentation.
> :memo: Updated the list of implemented design automation algorithms

- .github/codeql-config.yml
- include/fiction/algorithms/physical_design/exact.hpp
- include/fiction/algorithms/physical_design/one_pass_synthesis.hpp
- include/fiction/algorithms/simulation/sidb/quicksim.hpp
- include/fiction/layouts/bounding_box.hpp
- test/algorithms/network_transformation/network_conversion.cpp
- test/algorithms/path_finding/distance.cpp
- test/algorithms/simulation/sidb/minimum_energy.cpp
- test/algorithms/simulation/sidb/time_to_solution.cpp
- test/technology/charge_distribution_surface.cpp
This PR fixes warnings and notes by CodeQL. Furthermore, some overly strict CodeQL checks have been disabled because they lead to false positives.
Fixes #140
> :rotating_light: Fixed warnings and notes brought up by CodeQL

- experiments/color_routing/color_routing.cpp
- include/fiction/io/csv_writer.hpp
- include/fiction/io/dot_drawers.hpp
- include/fiction/io/network_reader.hpp
- include/fiction/io/read_fqca_layout.hpp
- include/fiction/io/read_sidb_surface_defects.hpp
- include/fiction/io/write_qcc_layout.hpp
- include/fiction/layouts/cell_level_layout.hpp
- include/fiction/layouts/clocking_scheme.hpp
This PR improves the performance of many string-based functions by switching to `std::string_view` and thus avoiding string copy costs.
> :zap: Utilize `std::string_view` instead of `std::string` in many places to improve performance

- CMakeLists.txt
- cli/CMakeLists.txt
- experiments/CMakeLists.txt
- include/fiction/technology/sidb_charge_state.hpp
- test/CMakeLists.txt
This PR fixes some linker issues that occurred because non-template functions were not `inline`d. Furthermore, name collisions in CMake are minimized when *fiction* is used as a library by renaming `project_options` to `fiction_project_options` and `project_warnings` to `fiction_project_warnings`.
> :rotating_light: Fixes for linker errors and CMake name collisions

- cmake/StandardProjectSettings.cmake
Using fiction as a header only library in qmap results in an cmake error due to multiple IPO checks.
> 🚨 Fixed error message from multiple IPO Checks 

- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
The GitHub Actions runners received some updated compiler versions while others were discontinued, e.g., `g++-9` on macOS. This PR updates the compiler versions for our CI runs.
> :construction_worker: Updated compilers on GitHub Actions to match latest runner versions

- include/fiction/utils/name_utils.hpp
Remove excess template parameter `T` when invoking `restore_names()` without a mapping of signals from `ntk_src` to `ntk_dest`.
> :bug: Removed excess template parameter `typename T`

- include/fiction/technology/sidb_charge_state.hpp
- test/technology/sidb_charge_state.cpp
This PR adds tests for the functions associated with `sidb_charge_state` and restructures the respective header a bit.
> :art: Restructured `sidb_charge_state` and added tests

- include/fiction/algorithms/simulation/sidb/sidb_simulation_parameters.hpp
- include/fiction/technology/charge_distribution_surface.hpp
- include/fiction/technology/sidb_nm_position.hpp
- test/technology/charge_distribution_surface.cpp
Redefinition of ``sidb_nm_position``. The return value was previously in meters and was changed to nanometers for consistency.
> redefinition of sidb_nm_position

- include/fiction/algorithms/simulation/sidb/sidb_simulation_parameters.hpp
- include/fiction/technology/charge_distribution_surface.hpp
- test/technology/charge_distribution_surface.cpp
This PR changes the unit of ``lambda_tf`` (parameter for the physical simulation of SiDBs) from meter to nanometer.
> :art: Changed the unit of the lambda-tf physical parameter from meter to nanometer

- .github/workflows/pyfiction-pypi-deployment.yml
- .github/workflows/python-bindings.yml
- bindings/pyfiction/README.md
- bindings/pyfiction/test/algorithms/physical_design/test_apply_gate_library.py
- bindings/pyfiction/test/algorithms/physical_design/test_exact.py
- pyproject.toml
Use `python-dotenv` to load environment variables from `.env`.
> 🐛 Fix test skips based on Z3

- .clang-format
- .github/workflows/clang-format.yml
- .github/workflows/clang-tidy-review.yml
- experiments/bestagon/bestagon.cpp
- experiments/color_routing/color_routing.cpp
- experiments/defect_aware_physical_design/defect_aware_physical_design.cpp
- experiments/defect_aware_physical_design/generate_defective_surface.py
- experiments/libfiction_demo.cpp
- include/fiction/algorithms/path_finding/a_star.hpp
- include/fiction/algorithms/path_finding/jump_point_search.hpp
- include/fiction/algorithms/physical_design/one_pass_synthesis.hpp
- include/fiction/io/read_fqca_layout.hpp
- include/fiction/io/write_qcc_layout.hpp
- include/fiction/io/write_qll_layout.hpp
- test/algorithms/path_finding/a_star.cpp
- test/algorithms/path_finding/enumerate_all_paths.cpp
- test/algorithms/path_finding/jump_point_search.cpp
- test/algorithms/path_finding/k_shortest_paths.cpp
- test/algorithms/physical_design/exact.cpp
- test/algorithms/physical_design/one_pass_synthesis.cpp
This PR extends the ClangFormat configuration to standardize all line endings to use `LF`. It also reformats the project using ClangFormat 17.
> :sparkles: Make ClangFormat aware of different line ending types and enforce `LF`

- include/fiction/io/write_sqd_sim_result.hpp
- test/io/write_sqd_sim_result.cpp
The state count is fixed to ``3`` to provide SiQAD compatibility (state count two is not supported by SiQAD yet).
> :art: Ensured SiQAD compatibility of SiDB simulation result writer

- .readthedocs.yml
This PR adds the specification of the build OS to prevent sphinx issue. Due to a latest update of sphinx, readthedocs are not build anymore (https://github.com/readthedocs/readthedocs-docker-images/issues/194).
> :bug: Specify build OS in readthedocs

- .github/workflows/docker-image.yml
- Dockerfile
The Docker workflow broke for some reason. This PR fixes it by installing Z3 via `pip` instead of doing the full build from scratch. At the same time, this change also significantly reduces Docker build times. Also, this PR changes the underlying Linux image from Alpine to Ubuntu.
> :green_heart: Fixed the Docker CI by installing Z3 via `pip`

- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/ubuntu.yml
- Dockerfile
Use `mold` instead of `ld` for faster link times.
> :zap: Use `mold` instead of `ld` for faster link times

- include/fiction/traits.hpp
- test/technology/charge_distribution_surface.cpp
`charge_distribution_surface` wasn't recognized by `is_cell_level_layout`. This PR fixes that behavior and adds respective trait tests.
> :bug: Fixed an issue with `charge_distribution_surface` not being recognized as a `cell_level_layout`

- docs/io/visualization.rst
- include/fiction/io/print_layout.hpp
- test/io/print_layout.cpp
This PR introduces a unified `print_layout` function that is easier to use than the previous ones.
> :sparkles: Added a unified `print_layout` function

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- Dockerfile
- README.md
- docs/contributing.rst
- docs/publications.rst
- docs/support.rst
- include/fiction/algorithms/physical_design/hexagonalization.hpp
- include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
- include/fiction/algorithms/simulation/sidb/quicksim.hpp
- include/fiction/utils/version_info.hpp.in
The move to @cda-tum left behind some inconsistencies in *fiction*'s documentation. This PR attempts to fix them while also restructuring the tracking of publications and their respective bibTeX files.
> :memo: Fixed remaining fragments from the move to `cda-tum` and adjusted the tracking of publications

- include/fiction/layouts/obstruction_layout.hpp
- test/algorithms/verification/equivalence_checking.cpp
This PR fixes unintended behavior, namely that `equivalence_checking` and `gate_level_drvs` could not be executed on `obstruction_layout` objections.
> :bug: Fix `equivalence_checking` on `obstruction_layout` objects

- include/fiction/algorithms/path_finding/distance.hpp
- test/algorithms/path_finding/distance.cpp
- test/algorithms/path_finding/distance_map.cpp
This PR fixes a potential overflow bug in `twoddwave_distance`.
> :bug: 2DDWave Distance Fix

- .github/workflows/clang-format.yml
- .github/workflows/clang-tidy-review.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/docker-image.yml
- .github/workflows/macos.yml
- .github/workflows/release-drafter.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
Added concurrency settings to each GitHub workflow file to prevent multiple runs of the same workflow on the same branch. This significantly optimizes resource usage, especially when multiple subsequent changes are pushed to the same branch.
This cancels in-progress runs on PRs, but still runs CI on every commit when not in a PR. This way every commit on main is tested, while duplicate work is reduced for PRs.
> 🔧 enable GitHub workflow concurrency

- docs/algorithms/path_finding.rst
- include/fiction/algorithms/graph/generate_edge_intersection_graph.hpp
- include/fiction/algorithms/path_finding/a_star.hpp
- include/fiction/algorithms/path_finding/enumerate_all_paths.hpp
- include/fiction/algorithms/path_finding/jump_point_search.hpp
- include/fiction/algorithms/path_finding/k_shortest_paths.hpp
- include/fiction/algorithms/physical_design/orthogonal.hpp
- include/fiction/algorithms/properties/critical_path_length_and_throughput.hpp
- test/algorithms/path_finding/a_star.cpp
- test/algorithms/path_finding/distance.cpp
- test/algorithms/path_finding/enumerate_all_paths.cpp
- test/algorithms/path_finding/jump_point_search.cpp
- test/algorithms/path_finding/k_shortest_paths.cpp
This PR increases the versatility of all path-finding algorithms by enabling them on different layout abstractions. Initially, path-finding was intended to be used exclusively in routing. Thus, it made sense to enforce clocked layouts as underlying data structures. However, it became evident that pathfinding can be applied more versatilely than anticipated initially. Therefore, this PR enables all path-finding algorithms on coordinate layouts as well. They automatically detect the most strict level of abstraction that a given layout implements and perform routing on that level. Alternatively, they can always be downcasted for the function call to strip a higher abstraction level if so desired.
> :sparkles: Enhanced pathfinding versatility

- cli/cmd/physical_design/hex.hpp
- experiments/hexagonalization/hexagonalization.cpp
- include/fiction/algorithms/physical_design/hexagonalization.hpp
- include/fiction/algorithms/physical_design/post_layout_optimization.hpp
- test/algorithms/physical_design/hexagonalization.cpp
- test/algorithms/physical_design/post_layout_optimization.cpp
Fixed a `nullptr` dereference bug.
> :bug: Fixed a `nullptr` dereference bug

- .gitmodules
- libs/CMakeLists.txt
Recently, the Windows CI broke. This PR fixes it by updating the `alice` library to a fork of our own. Its `pybind11` version was way too old and broke on modern CMake versions. Therefore, we're including our own `pybind11` now.
> :construction_worker: Fix Windows CI

- bindings/pyfiction/include/pyfiction/algorithms/physical_design/hexagonalization.hpp
- bindings/pyfiction/include/pyfiction/layouts/cell_level_layout.hpp
- bindings/pyfiction/include/pyfiction/types.hpp
- bindings/pyfiction/pyfiction.cpp
- bindings/pyfiction/test/algorithms/physical_design/test_hexagonalization.py
- docs/algorithms/hexagonalization.rst
Added the `hexagonalization` algorithm to `pyfiction`.
> ✨ Add hexagonalization algorithm to pyfiction

- include/fiction/layouts/clocking_scheme.hpp
- include/fiction/utils/stl_utils.hpp
This PR fixes minor oversights in two places that might have the possibility to slightly increase performance when heavily used.
1. Switched from dynamic to static allocation in `clocking_scheme.hpp`
2. Added missing `noexcept` annotations in `stl_utils.hpp`
> :art: Fix minor oversights by using `static constexpr` and `noexcept`

- bindings/pyfiction/include/pyfiction/io/read_fgl_layout.hpp
- bindings/pyfiction/include/pyfiction/io/write_fgl_layout.hpp
- bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- bindings/pyfiction/pyfiction.cpp
- bindings/pyfiction/test/io/__init__.py
- bindings/pyfiction/test/io/test_read_write_fgl_layout.py
- docs/io/input.rst
- docs/io/physical_simulation.rst
Expose gate-level layout reader and writer
> ✨ Expose gate-level layout reader and writer

- bindings/pyfiction/include/pyfiction/networks/logic_network.hpp
- bindings/pyfiction/test/networks/test_logic_network.py
Added the possibility to get the name of nodes in a logic network.
> ✨ Add naming utils to logic network

- include/fiction/algorithms/iter/gray_code_iterator.hpp
- include/fiction/technology/charge_distribution_surface.hpp
This PR fixes the compiler warning on ubuntu-20.04 with g++ related to the CDS.
> :rotating_light: Fix compiler warnings on ubuntu-20.04 with g++

- docs/algorithms/hexagonalization.rst
- experiments/hexagonalization/hexagonalization.cpp
- include/fiction/algorithms/physical_design/hexagonalization.hpp
- test/algorithms/physical_design/hexagonalization.cpp
New features:
- automatically remove empty columns on the left- and right-hand side of the hexagonal layout
- save runtime in a statistics object
- refactored types
> ✨Refactored the hexagonalization algorithm

- CMakeLists.txt
- cmake/Utilities.cmake
- cmake/VCEnvironment.cmake
This PR fixes a problem with VSC builds due to a missing CMake include.
> :green_heart: Fix VSC builds

- include/fiction/algorithms/simulation/sidb/quickexact.hpp
- include/fiction/technology/charge_distribution_surface.hpp
- test/algorithms/simulation/sidb/quickexact.cpp
- test/technology/charge_distribution_surface.cpp
This PR fixes an issue where the dependent cell can be positively charged even if the base number is set to two-state simulation.
@wlambooy Thanks for reporting this bug.
> 🐛 The dependent cell is now linked correctly to the simulation base number in SiDB simulation

- docs/technology/properties.rst
- experiments/defect_aware_physical_design/defect_aware_physical_design.cpp
- include/fiction/technology/area.hpp
This PR updates the atomic defect-aware SiDB physical design experiment in accordance with the final paper, which will be published at DATE 2024. 
In particular, the experiment script was not computing the bounding box of the generated layout, leading to confusing results.
> :alembic: Updated the atomic defect-aware SiDB physical design experiment in accordance with the final paper

- include/fiction/algorithms/simulation/sidb/operational_domain.hpp
- test/algorithms/simulation/sidb/operational_domain.cpp
This PR uses the correct y-direction boundary for Moore neighborhood. An appropriate test is added.
> 🐛 Correct y-direction boundary for Moore neighborhood

- .codecov.yml
Added a designated configuration file for Codecov because the user profile configuration does not apply anymore since the repo was moved.
> :open_umbrella: Added Codecov configuration file

- test/benchmark/simulation.cpp
This PR introduces a benchmark for ``QuickExact`` and ``QuickSim`` to measure the runtime.
> :sparkles: Benchmark for physical simulators.

- include/fiction/algorithms/physical_design/hexagonalization.hpp
Inputs and outputs have to be placed in the same order as specified in the network/ Cartesian layout.
> 🐛 Place inputs and outputs in the same order during hexagonalization

- include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
- test/algorithms/simulation/sidb/critical_temperature.cpp
This PR fixes a bug in the critical temperature simulation. The critical temperature value for a given input combination is only overwritten by the new value if the new value is lower.
> :bug: The critical temperature value will only be overwritten by the new value if the new value is lower.

- .github/workflows/macos.yml
This PR constitutes a hotfix for our macOS CI by disabling the installation of TBB under macOS 11 as it seems to no longer be supported.
> :green_heart: Hotfix for the macOS CI

- include/fiction/technology/sidb_surface.hpp
- test/technology/sidb_surface.cpp
This PR allows a given atomic defect to be overwritten/updated with a newly assigned one.
- ``phmap::parallel_flat_hash_map`` does not work as intended.
> 🐛 Atomic defect can be updated or new one can be assigned at specific coordinate.

- include/fiction/io/read_sqd_layout.hpp
- test/io/read_sqd_layout.cpp
`read_sqd_layout` now updates the aspect ratio properly for SiQAD-coordinate based layouts
> :bug: `read_sqd_layout` now updates the aspect ratio properly for SiQAD-coordinate based layouts

- cli/cmd/physical_design/exact.hpp
- include/fiction/algorithms/physical_design/exact.hpp
- test/algorithms/physical_design/exact.cpp
This PR adds an upper bound option for the total layout area to `exact` physical design.
> :sparkles: Added an upper bound option for the total layout area to `exact`

- include/fiction/algorithms/simulation/sidb/operational_domain.hpp
- test/algorithms/simulation/sidb/operational_domain.cpp
This PR fixes a potential floating-point error when converting a parameter point to a step point.
> 🐛 Fix floating-point errors.

- include/fiction/technology/charge_distribution_surface.hpp
- test/algorithms/simulation/sidb/quickexact.cpp
This PR fixes a major bug. The hopping energy from a neutrally to a positively charged SiDB was calculated incorrectly. Finally, this fix allows the successful simulation of positively charged SiDBs.
@samuelngsh I would strongly recommend to make this change in *SiQAD* as well. Many thanks!
> 🐛 Fixed hop energy calculation from neutral to positive SiDB

- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
This PR increases the build and test parallelism for Ubuntu and Windows CI to make use of the performance benefit of [GitHub's updated runners](https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/).
> :zap: Increased parallelism for building and testing in the Ubuntu and Windows workflows

- include/fiction/algorithms/simulation/sidb/operational_domain.hpp
This PR adds ``std::round()`` to mitigate floating point errors.
> 🐛 Add round-function to mitigate floating precision issues

- test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
- test/algorithms/simulation/sidb/quickexact.cpp
This PR adds one unit test for a special SiDB layout.
> :white_check_mark: Add more tests for 3-state simulation.

- .github/workflows/macos.yml
This PR adds ``macos-13`` and ``macos-14`` to the MacOS CI.
> :construction_worker: Update macOS CI to support Apple Silicon runners

- docs/algorithms/design_sidb_gates.rst
- docs/publications.rst
This PR adds the reference for the paper ``Minimal Design of SiDB Gates: An Optimal Basis for Circuits Based on Silicon Dangling Bonds.`` and changes the publication year of the other NANOARCH papers from 2023 to 2024.
> :memo: Add missing publication.

- include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
- test/algorithms/simulation/sidb/is_groundstate.cpp
- test/algorithms/simulation/sidb/time_to_solution.cpp
This PR fixes a bug in ``is_ground_state``. Previously, the wrong parameter was used for the calculation. This bug was already fixed in #380, but to ensure quick integration, this separate PR is created.
Fixes #392
> :bug: Use correct parameter in ``is_ground_state``.

- cli/cmd/technology/area.hpp
- cli/stores.hpp
- docs/technology/properties.rst
- experiments/bestagon/bestagon.cpp
- experiments/defect_aware_physical_design/defect_aware_physical_design.cpp
- experiments/hexagonalization/hexagonalization.cpp
- experiments/post_layout_optimization/post_layout_optimization.cpp
- include/fiction/algorithms/physical_design/exact.hpp
- include/fiction/algorithms/properties/critical_path_length_and_throughput.hpp
- include/fiction/algorithms/verification/equivalence_checking.hpp
- include/fiction/technology/area.hpp
- test/algorithms/physical_design/exact.cpp
- test/algorithms/properties/critical_path_length_and_throughput.cpp
- test/algorithms/verification/equivalence_checking.cpp
- test/utils/equivalence_checking_utils.hpp
This PR enhances the usability of a couple of older functions by adding return values. This breaks legacy code.
> :art: Usability improvement by return type adjustments

- include/fiction/algorithms/simulation/sidb/operational_domain.hpp
- include/fiction/technology/charge_distribution_surface.hpp
- test/algorithms/simulation/sidb/operational_domain.cpp
This PR fixes a non-deterministic failure of the operational domain unit tests on Ubuntu and Windows. This is fixed by checking that ``moore_neighborhood`` is not empty before selecting the front step point. It also ensures that ``x_min`` and ``y_min`` are part of the parameter space that is checked for operation.
> :bug: Include x_min and y_min in OpDomain and check non-emptyness of vector before accessing element.

- include/fiction/layouts/coordinates.hpp
- test/layouts/coordinates.cpp
- test/technology/sidb_nm_position.cpp
This pull request solves a problem in the ``to_siqad_coord`` function. When converting cube coordinates with negative y-values, it was giving incorrect results for siqad coordinates. This fix makes sure that the conversion works correctly, even with negative y-values.
> :bug: Fixed conversion of cube coordinate with negative y-value to SiQAD coordinate

- include/fiction/algorithms/simulation/sidb/operational_domain.hpp
- test/algorithms/simulation/sidb/operational_domain.cpp
This PR replaces the ``std::vector`` with a ``std::set`` to ensure uniqueness of sample points. It also updates the unit test and corrects the upper bound of the number of values of the operational domain when using contour tracing. Thanks to @wlambooy for finding and mentioning this! 🙏
> 🐛  Fix wrong values in unit test for OpDomain and introduce uniqueness set for sample points.

- .github/workflows/clang-tidy-review.yml
Clang-tidy did not exclude all files specified in the exclude pattern due to whitespaces, which are not stripped correctly.
Minimal code example taken from https://github.com/ZedThree/clang-tidy-review:
```
import fnmatch
def strip_enclosing_quotes(string: str) -> str:
"""Strip leading/trailing whitespace and remove any enclosing quotes"""
stripped = string.strip()
for quote in ['"', "'", '"']:
if stripped.startswith(quote) and stripped.endswith(quote):
stripped = stripped[1:-1]
return stripped
files = ['bindings/pyfiction/include/pyfiction/algorithms/physical_design/post_layout_optimization.hpp', 'bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp']
ex = '*/pyfiction/pybind11_mkdoc_docstrings.hpp, */pyfiction/documentation.hpp'
exclude = …
```
> 🐛 Fix exclude pattern in clang-tidy-review.yml

- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
This PR restructures the CI system to reduce the amount of runners spawned.
- Deprecate macOS-12 support
- Merge Debug and Release pipelines for all workflows into single runners for performance reasons
Additional changes:
- Bump Python in the runners to 3.10
> :construction_worker: CI Restructuring

- .github/workflows/pyfiction-pypi-deployment.yml
Only trigger `pyfiction-pypi-deployment` when specific files are changed, similar to `python-binding.yml`
> 👷 Limit triggering of the pyfiction deployment CI 

- README.md
Use absolute instead of relative paths to images.
> 🐛 Images on PyPI

- experiments/sidb_simulation/runtime_analysis.cpp
- include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
This PR adds a script for an experiment to measure the runtime of _ExGS_ and _QuickExact_ and the time-to-solution of _QuickSim_ for the Bestagon gates.
> :alembic: Added a runtime experiment script.

- bindings/pyfiction/include/pyfiction/algorithms/physical_design/design_sidb_gates.hpp
- bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/critical_temperature.hpp
- bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/detect_bdl_pairs.hpp
- bindings/pyfiction/test/algorithms/physical_design/test_design_sidb_gates.py
- bindings/pyfiction/test/algorithms/simulation/sidb/test_critical_temperature.py
- bindings/pyfiction/test/algorithms/simulation/sidb/test_detect_bdl_pairs.py
- docs/algorithms/sidb_simulation.rst
- docs/io/physical_simulation.rst
- include/fiction/algorithms/iter/bdl_input_iterator.hpp
- include/fiction/algorithms/physical_design/design_sidb_gates.hpp
- include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
- include/fiction/algorithms/simulation/sidb/detect_bdl_pairs.hpp
- include/fiction/algorithms/simulation/sidb/is_operational.hpp
- include/fiction/algorithms/simulation/sidb/operational_domain.hpp
- test/algorithms/physical_design/design_sidb_gates.cpp
This PR introduces some minor fixes in pyfiction. Also, it is no longer needed to distinguish between the ``100`` and ``111`` SiDB lattice when detecting BDL pairs.
> :snake: Minor fixes and change of template parameter of BDL pairs.

- .github/workflows/pyfiction-docstring-generator.yml
The python docstring generator stopped working on PRs from forks. Adding `on: pull_request` should fix that.
> 📝 Run python docstring generator on forks during PRs

- .github/workflows/pyfiction-docstring-generator.yml
The docstring generator workflow successfully runs when merging branches originating from ``upstream-main``. However, it fails to push docstrings during workflow execution for branches originating from ``fork-main`` due to detached branches.
This PR resolves the issue by specifying the target branch for pushing docstrings.
Thanks @simon1hofmann for helping to figure this out!
> 📝 Update docstring generator to include target branch for push

- include/fiction/algorithms/physical_design/post_layout_optimization.hpp
- include/fiction/algorithms/physical_design/wiring_reduction.hpp
Fixed compiler warnings:
`warning: declaration of 'x_offset' shadows a lambda capture [-Wshadow]`
`warning: declaration of 'y_offset' shadows a lambda capture [-Wshadow]`
`warning: conversion from ‘long unsigned int’ to ‘unsigned int:31’ may change value [-Wconversion]`
> 🚨 Fixed compiler warnings

- cmake/Sanitizers.cmake
This PR introduces a warning when Leak Sanitizer is used with Apple Clang, as it is incompatible with this compiler.
> :children_crossing: Add warning for leak sanitizer usage with AppleClang

- .github/workflows/macos.yml
- .github/workflows/windows.yml
This PR updates the Windows and MacOS CI workflow to include Python 3.10 and pip caching. This change is required due to pybind's removal (https://github.com/pybind/pybind11/commit/723307283ed7dc03c901fba1da1127c7b16a4a0d) of support for Python versions earlier than 3.8.
> :green_heart: Added Python Setup to CI Workflow

- .github/workflows/macos.yml
- bindings/pyfiction/include/pyfiction/layouts/cell_level_layout.hpp
- bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- bindings/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
- bindings/pyfiction/include/pyfiction/utils/layout_utils.hpp
- docs/utils/utils.rst
- include/fiction/io/print_layout.hpp
- include/fiction/utils/layout_utils.hpp
- test/algorithms/iter/bdl_input_iterator.cpp
- test/algorithms/physical_design/design_sidb_gates.cpp
- test/algorithms/simulation/sidb/displacement_robustness_domain.cpp
- test/io/print_layout.cpp
- test/utils/layout_utils.cpp
This PR bumps the GCC versions on macOS CIs due to incompatibility with the latest GitHub runner software package updates.
Additionally, it introduces a workaround for a compiler error in GCC 14 that occured on the `convert_to_siqad_coordinates` function. Many thanks to @Drewniok for this fix!
> :construction_worker: Update GCC versions on macOS CIs

- .github/workflows/ubuntu.yml
Dropped `ubuntu-20.04` and added `ubuntu-24.04`. Additionally, updated the C++ compilers to newer versions
> :construction_worker: Updated the Ubuntu CI to include 24.04 and newer compiler versions

- docs/algorithms/exact.rst
`exact` and `exact_with_blacklist` were not rendered properly in the RST documentation on ReadTheDocs. This PR fixes that.
> :bug: Fixed a RST documentation bug that  prevented `exact` and `exact_with_blacklist` to be rendered properly

- .github/workflows/clang-tidy-review.yml
- bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
- include/fiction/algorithms/physical_design/orthogonal.hpp
- test/algorithms/physical_design/graph_oriented_layout_design.cpp
Applied `clang-tidy` suggestions`.
> 🚨 clang-tidy warnings

- bindings/pyfiction/include/pyfiction/algorithms/path_finding/distance.hpp
- bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- bindings/pyfiction/test/algorithms/path_finding/test_distance.py
- docs/algorithms/path_finding.rst
- docs/changelog.rst
- include/fiction/algorithms/path_finding/distance.hpp
- test/algorithms/path_finding/distance.cpp
This PR adds the [squared Euclidean](https://en.wikipedia.org/wiki/Euclidean_distance#Squared_Euclidean_distance) and the [Chebyshev](https://en.wikipedia.org/wiki/Chebyshev_distance) distance functions to the list of pre-defined ones.
Squared Euclidean is useful when formulating optimization problems that require gradient computation due to its differentiability. Chebyshev on the other hand does not over-account for diagonal moves on non-Cartesian grids.
> :sparkles: Squared Euclidean and Chebyshev distance functions

- docs/algorithms/sidb_simulation.rst
`operational_domain_value_range` was missing from the C++ part of the RTD documentation. Additionally, `dimer_displacement_policy` was redundant in the C++ documentation but missing the Python one. This PR fixes these oversights.
> :memo: Fix a few oversights in the RTD documentation of SiDB simulation functionality

- bindings/pyfiction/include/pyfiction/inout/write_svg_layout.hpp
- cli/cmd/physical_design/ortho.hpp
- docs/algorithms/sidb_simulation.rst
- include/fiction/algorithms/physical_design/apply_gate_library.hpp
- include/fiction/io/write_svg_layout.hpp
- include/fiction/layouts/clocked_layout.hpp
- include/fiction/layouts/clocking_scheme.hpp
#317 broke `apply_gate_library` as it would no longer copy the clocking scheme from the given `gate_level_layout` to the newly created `cell_level_layout`. This PR fixes the breaking change and also cleans up some related code that I came across while debugging.
> :bug: Fixed disappearing clocking schemes when applying a gate library

- include/fiction/algorithms/optimization/simulated_annealing.hpp
- include/fiction/algorithms/physical_design/design_sidb_gates.hpp
- include/fiction/algorithms/physical_design/on_the_fly_circuit_design_on_defective_surface.hpp
- include/fiction/algorithms/simulation/sidb/assess_physical_population_stability.hpp
- include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
- include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
- include/fiction/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.hpp
- include/fiction/algorithms/simulation/sidb/occupation_probability_of_excited_states.hpp
- include/fiction/algorithms/simulation/sidb/quickexact.hpp
- include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
- include/fiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
- include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
- include/fiction/io/write_sqd_layout.hpp
- include/fiction/io/write_sqd_sim_result.hpp
- include/fiction/layouts/bounding_box.hpp
- include/fiction/technology/sidb_defects.hpp
This PR implements a few ``clang-tidy`` warnings.
> :rotating_light: Fixed clang-tidy warnings.

- .github/workflows/codeql-analysis.yml
It seems that clang++-11 is deprecated, leaving the CodeQL analyse cpp CI to fail.
> :arrow_up: CodeQL now uses `clang++-13`

- include/fiction/algorithms/physical_design/design_sidb_gates.hpp
- include/fiction/technology/charge_distribution_surface.hpp
- test/algorithms/physical_design/design_sidb_gates.cpp
- test/technology/charge_distribution_surface.cpp
This PR fixes two bugs:
1. It is checked now if a defect is charged when adding it to a cds.
2. The termination condition for _Automatic Exhaustive Gate Design_ was missing.
Thanks to @wlambooy for reporting a strange behavior of on-the-fly defect aware layout design.
> 🐛 Fix neutral defect handling in CDS and correct gate design termination condition.

- bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/detect_bdl_wires.hpp
- bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- docs/algorithms/sidb_simulation.rst
- include/fiction/algorithms/simulation/sidb/detect_bdl_wires.hpp
Fixed some minor oversights in the documentation of BDL wire detection. Some documented functions did not exist anymore while other structs were not captured.
> :memo: Fix documentation for BDL wire detection

- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/macos.yml
- .github/workflows/pyfiction-docstring-generator.yml
- .github/workflows/pyfiction-pypi-deployment.yml
- .github/workflows/python-bindings.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
This PR updates all related GitHub Action CIs to support Python 3.13.
> :snake: Support Python 3.13

- bindings/pyfiction/include/pyfiction/algorithms/iter/bdl_input_iterator.hpp
- bindings/pyfiction/include/pyfiction/algorithms/simulation/logic_simulation.hpp
- bindings/pyfiction/include/pyfiction/layouts/coordinates.hpp
- bindings/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
- bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- include/fiction/algorithms/graph/graph_coloring.hpp
- include/fiction/algorithms/iter/bdl_input_iterator.hpp
- include/fiction/algorithms/physical_design/apply_gate_library.hpp
- include/fiction/algorithms/simulation/sidb/detect_bdl_wires.hpp
- include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
- include/fiction/io/read_sidb_surface_defects.hpp
- include/fiction/layouts/clocking_scheme.hpp
- include/fiction/layouts/gate_level_layout.hpp
- include/fiction/technology/charge_distribution_surface.hpp
- include/fiction/technology/sidb_on_the_fly_gate_library.hpp
- include/fiction/utils/layout_utils.hpp
- test/algorithms/simulation/sidb/displacement_robustness_domain.cpp
- test/io/read_sqd_layout.cpp
This PR fixes compiler and linter warnings throughout the project.
> :rotating_light: Fixed compiler and linter warnings

- .dockerignore
- .github/workflows/docker-image.yml
- Dockerfile
- README.md
This PR updates the Docker workflow. Most notably, the following changes are made:
- `.dockerignore`:
- added new file types and folders, yielding smaller image sizes
- fixed paths, applying filter rules to sub-directories, yielding smaller image sizes
- `Dockerfile`:
- set Ubuntu version to a specific LTS release
- added labels with meta info
- enforced a clean-up after build, yielding smaller image sizes
- initiated all installs and builds as a non-root user
- Docker GitHub CI:
- added the ability to publish images to DockerHub
> :whale: Improved the Docker workflow

- docs/changelog.rst
- include/fiction/algorithms/physical_design/post_layout_optimization.hpp
- include/fiction/algorithms/physical_design/wiring_reduction.hpp
- test/algorithms/physical_design/post_layout_optimization.cpp
- test/algorithms/physical_design/wiring_reduction.cpp
- test/benchmark/post_layout_optimization.cpp
- test/utils/blueprints/layout_blueprints.hpp
- changed bounding box calculation in `wiring_reduction` to take empty columns /rows to the left/top of other gates into account
- during `post-layout optimization`, PIs can be moved even if connected to its fanout directly
> 🐛 Adapted optimization algorithms to handle layouts with PIs not placed at borders

- .github/workflows/macos.yml
This fixed a CI issue where the XCode version setup led to an error because it was no longer available on the macOS 14 runners. Since macOS didn't require this explicit version setup anyway, this PR removes it accordingly.
> :green_heart: Remove explicit XCode version setup for macOS 13

- bindings/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
- bindings/pyfiction/test/layouts/test_gate_level_layout.py
Exposed `layout.get_name(signal)` to `pyfiction`.
> :snake: Expose `layout.get_name`

- .github/workflows/pyfiction-pypi-deployment.yml
This PR updates the PyPI deployment script to attest build provenance to the wheels and sdist.
> :construction_worker: Attest build provenance to our wheels and sdist

- Dockerfile
This PR streamlines the `Dockerfile` metadata labels to be compatible with the [Open Container Initiative (OCI)](https://opencontainers.org/) standard tags found here: https://github.com/opencontainers/image-spec/blob/main/annotations.md
> :whale: Unify Dockerfile labels to conform to the Open Container Initiative (OCI) standard

- include/fiction/io/print_layout.hpp
- include/fiction/io/write_svg_layout.hpp
- include/fiction/layouts/coordinates.hpp
- include/fiction/technology/cell_ports.hpp
This PR enforces the use of `fmt::runtime` in scenarios where dynamic formatting strings are used with the `{fmt}` library in order to fix compilation errors when these functions are used in `consteval` contexts.
> :bug: Enforce runtime evaluation of dynamic formatting strings to fix `consteval` contexts

- bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- docs/changelog.rst
- include/fiction/algorithms/physical_design/design_sidb_gates.hpp
- include/fiction/algorithms/simulation/sidb/is_operational.hpp
- test/algorithms/physical_design/design_sidb_gates.cpp
- test/utils/blueprints/layout_blueprints.hpp
This PR fixes the following bug in the ``design_sidb_gates`` function: When using a gate skeleton with wires facing east, the gate design would not work. 
The error occurred during the second pruning step when using _QuickCell_ for designing SiDB gates. During this step, the feasibility of the physical validity is checked by toggling through different input patterns and adjusting the charge distribution of the I/O pins accordingly. However, the logic failed for I/O pins facing east because this specific case was not accounted for in the if statement. This is now fixed.
> :bug: Fixed ``design_sidb_gates`` function for skeletons with east-facing I/O pins.

- bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- cli/stores.hpp
`is_offset_ucoord_v` expects a `CoordinateType` but instead a `Lyt` type was provided.
> 🐛 Fixed CLI `show` command

- .readthedocs.yml
- docs/getting_started.rst
- noxfile.py
- pyproject.toml
This PR removes support for Python 3.8 because that version reached end-of-life almost 3 months ago. See https://devguide.python.org/versions/ for details on Python's release schedule.
> :snake: Drop Python 3.8 support due to its end-of-life status

- bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- include/fiction/algorithms/physical_design/apply_gate_library.hpp
When applying a gate library to a hexagonal gate-level layout, the resulting cell-level layout would not have the right sizing.
The implemented fix now supports tiling geometries in which all even rows/columns are aligned and all odd rows/columns are aligned.
> :bug: Fixed layout resizing in `apply_gate_library`

- bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/operational_domain.hpp
- bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_operational_domain.py
- include/fiction/algorithms/simulation/sidb/operational_domain.hpp
This PR corrects the python bindings for the critical temperature domain computation. Previously, the operational domain functions were mistakenly used instead of the appropriate critical temperature domain functions.
> :snake: Fixed python bindings for critical temperature domain

- bindings/mnt/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
- experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis_bestagon_gates.cpp
- include/fiction/algorithms/simulation/sidb/clustercomplete.hpp
- include/fiction/algorithms/simulation/sidb/quickexact.hpp
- include/fiction/algorithms/simulation/sidb/quicksim.hpp
- include/fiction/technology/charge_distribution_surface.hpp
- test/algorithms/simulation/sidb/quicksim.cpp
- test/benchmark/simulation.cpp
- test/technology/charge_distribution_surface.cpp
This PR introduces a minor refactor of _QuickSim_. The key update involves removing the hardcoded number ``1.5`` in the upper limit calculation, which was originally implemented to accelerate the simulation of SiDB gates. While this approach proved effective in most scenarios, it could lead to rare edge cases causing unexpected behavior. To enhance reliability, this adjustment eliminates the magic number. Importantly, the overall performance remains significantly improved compared to the results presented in _QuickSim: Efficient and Accurate Physical Simulation of Silicon Dangling Bond Logic_ (https://ieeexplore.ieee.org/document/10231266).
> :art: Refactored ``QuickSim`` to remove magic number for upper limit calculation

- bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
- bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- bindings/mnt/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
- bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_random_sidb_layout_generator.py
- experiments/random_sidb_layout_generation/random_sidb_layout_generation.cpp
- experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis_layouts_with_possible_positive_sidbs.cpp
- include/fiction/algorithms/physical_design/design_sidb_gates.hpp
- include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
- test/algorithms/simulation/sidb/random_sidb_layout_generator.cpp
This PR refactors the functions responsible for designing random SiDB layouts. If the design process fails, ``std::nullopt`` is now returned instead of an empty layout.
> :art: Refactored random layout design functions

- include/fiction/layouts/gate_level_layout.hpp
- test/layouts/gate_level_layout.cpp
Deleting a wire can decrease the number of crossings in two ways:
1. Deleted wire was in the crossing layer and had a wire in the ground layer
2. Deleted wire was in the ground layer and had a wire in the crossing layer
Similar adding a wire can increase the number of crossings in two ways:
1. Added wire is in the crossing layer and there is already a wire in the ground layer
2. Added wire is in the ground layer and there is already a wire in the crossing layer
The previous implementation only covered the first cases.
Thanks a lot to @Drewniok and @samuelshng for spotting this bug.
> 🐛 Number of crossings calculation

- bindings/mnt/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
- bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- include/fiction/io/read_fgl_layout.hpp
- include/fiction/io/write_fgl_layout.hpp
- include/fiction/layouts/gate_level_layout.hpp
- test/algorithms/verification/design_rule_violations.cpp
- test/io/read_fgl_layout.cpp
- test/layouts/gate_level_layout.cpp
- test/utils/blueprints/layout_blueprints.hpp
LT, LE, GT, and LE gates have been disregarded in `write_fgl_layout` and `read_fgl_layout`. This PR addresses this shortcoming. Furthermore, there was an issue with the internal representation of these gate types in `gate_level_layout`, where their truth tables were stored in the wrong format. This has been fixed, too.
> :bug: Fixed LT, LE, GT, and LE gate handling in `gate_level_layout` and `write_`/`read_fgl_layout`

- bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
- bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
- include/fiction/algorithms/simulation/sidb/is_operational.hpp
- include/fiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
- include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
This PR ensures that _ClusterComplete_ cannot be selected as the simulation engine when ALGLIB is disabled.
> 🐛 Exclude ClusterComplete from simulation engine selection when ALGLIB is disabled

- include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
- include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
- test/algorithms/simulation/sidb/time_to_solution.cpp
This PR fixes two bugs: 
1.) The charge index calculation was done wrongly for ``groundstates()`` for charge distributions with base = 3. This is now fixed by using ``charge_distribution_to_index_general()``. 
2.) The automatic base detection in the TTS calculation was activated. Hence, the heuristic and exact simulations might be conducted with different bases. This is not desired. The automatic base detection is now turned off, ensuring that the same base is used in both cases.
> :bug: Use correct function for charge index calculation and fix base for TTS calculation

- .github/renovate.json5
- .readthedocs.yml
- docs/requirements.txt
- pyproject.toml
- uv.lock
This PR modernizes the documentation builds. It migrates the RTD builds from `pip` to `uv`. Additionally, unnecessary RTD builds are skipped entirely. Since this change removes the last need for `pip` from the project, the Renovate Bot config could also be simplified.
> :construction_worker: Set up documentation builds with `uv`

- bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/operational_domain.hpp
- bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_operational_domain.py
- bindings/mnt/pyfiction/test/inout/test_write_operational_domain.py
- include/fiction/algorithms/simulation/sidb/operational_domain.hpp
- include/fiction/algorithms/simulation/sidb/sidb_simulation_domain.hpp
This PR adds a dictionary-like function interface to the Python bindings of  `operational_domain` and `critical_temperature_domain`.
> :snake: Add Pythonic dictionary-like interfaces to `operational_domain` and `critical_temperature_domain`

- bindings/mnt/pyfiction/include/pyfiction/algorithms/physical_design/design_sidb_gates.hpp
- bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
- bindings/mnt/pyfiction/test/algorithms/physical_design/test_design_sidb_gates.py
- include/fiction/algorithms/physical_design/design_sidb_gates.hpp
- include/fiction/algorithms/simulation/sidb/is_operational.hpp
- test/algorithms/physical_design/design_sidb_gates.cpp
- test/algorithms/simulation/sidb/is_operational.cpp
This PR introduces two main enhancements. First, pruning techniques have been enabled for all overloaded versions of the ``is_operational`` function. Second, the gate design function has been extended to include a new method, ``PRUNING_BASED``. This method conducts pruning (same as in _QuickCell_) without relying on physical simulation, making it particularly useful in scenarios where gate/standard cell candidates are designed without simulation. However, this approach may lead to false positives as a trade-off for increased performance.
> 🎨 Small changes in ``is_operational`` and added ``PRUNING_BASED`` option to gate design

- .github/workflows/clang-tidy-review.yml
This runs the workflow in the context of the base repository for proper permission management.
> :construction_worker: Update clang-tidy CI to use the `pull_request_target` trigger
